### ISSUE TITLE
request: truetype font Name() API

### ISSUE THREAD

**Issue by GoogleCodeExporter** [golang/freetype#10]
```
I would like to be able to get at the font name(s) stored in the truetype in 
the font file. 
```

Original issue reported on code.google.com by `snesse...@gmail.com` on 29 May 2014 at 12:39

**Comment by stephenwithav** [comment]
Mind if I take a crack at this?

**Comment by nigeltao** [comment]
Go for it.

github.com/golang/freetype doesn't use gerrit, but please still complete the Contributor License Agreement if you haven't already done so: https://golang.org/doc/contribute.html#tmp_6

**Comment by stephenwithav** [comment]
CLA signed.

The pull request will be in later today.

**Comment by nigeltao** [comment]
Fixed by https://github.com/golang/freetype/commit/995030b974eebe607d1115b7ac9e38ea9a1bc809
