### ISSUE TITLE
Fix TTC parsing

### ISSUE THREAD

**Issue by GoogleCodeExporter** [golang/freetype#11]
```
I have no idea how to submit patches, so forgive me if this is an inappropriate 
venue.

Attached is a patch fixing TTC parsing.
The constant 12 was hardcoded instead of using `offset`.

Tested on a TTC v2.0 file, I don't have a v1.0 file to test on but based on 
what I understand of the file format I don't think there should be any issues 
with that.
```

Original issue reported on code.google.com by `magician...@gmail.com` on 10 Sep 2014 at 4:30

Attachments:
- [freetype-go.patch](https://storage.googleapis.com/google-code-attachments/freetype-go/issue-11/comment-0/freetype-go.patch)

**Comment by mattn** [comment]
I tested this patch. And this change can parse TTC v2.

**Comment by mattn** [comment]
If I make pr from this change, would you merge?

**Comment by nigeltao** [comment]
Yes.
