### ISSUE TITLE
FullHinting and PointToFix32

### ISSUE THREAD

**Issue by fnkr** [golang/freetype#20]
I upgraded the package and now I am missing `freetype.FullHinting` and `freetype.NewContext().PointToFix32`. How to fix this?

**Comment by nigeltao** [comment]
See https://groups.google.com/d/topic/golang-nuts/tr-MftD7kbo/discussion

For example, in that discussion, I say
truetype.NoHinting becomes font.HintingNone
you will need to import "golang.org/x/image/font".

As for PointToFix32, you will need to make your own calculation based on your DPI level. Something like:

func PointToInt26_6(x float64) fixed.Int26_6 {
        return fixed.Int26_6(x * float64(c.dpi) * (64.0 / 72.0))
}

**Comment by fnkr** [comment]
Can you help me a little bit more, please?

I'm trying to get the text in the middle of the image.
Here is what I did:
```go
emSquarePix := int(c.PointToFix32(float64(fontSize)) >> 9) * 1000 / 1333
textCount := utf8.RuneCountInString(text)

x0 := (width - textCount*emSquarePix) / 2
y0 := height / 2 * 10 / 9

pt := freetype.Pt(x0, y0)
c.DrawString(text, pt)
```

**Comment by nigeltao** [comment]
Change
c.PointToFix32(etc)
to
PointToInt26_6(etc, dpi)

where PointToInt26_6 is

func PointToInt26_6(x, dpi float64) fixed.Int26_6 {
  return fixed.Int26_6(x * dpi * (64.0 / 72.0))
}

If you don't know what DPI to use, pass 72, but if it's always 72, the whole thing simplifies to:

scaleX := float64(width)*64*maxTextBoundsToImageRatioX / float64(textExtent.X)

**Comment by fnkr** [comment]
It compiles but the text is not in the middle of the image anymore.

![image](https://cloud.githubusercontent.com/assets/616991/9769303/96778d84-5729-11e5-89af-471ca6e1a980.png)

```go
const (
	maxTextBoundsToImageRatioY = 0.23
	maxTextBoundsToImageRatioX = 0.64
	dpi                        = 72.00
	testFontSize               = 1.00 // use heigher values (>=100) when hinting enabled
)
```

```go
// first draw with testFontSize to get the text extent
var textExtent fixed.Point26_6
drawPoint := freetype.Pt(0, int(PointToInt26_6(testFontSize, dpi)>>8))
textExtent, err = c.DrawString(text, drawPoint)
if err != nil {
    return nil, err
}

// calculate font scales to stay within the bounds
scaleX := float64(PointToInt26_6(float64(width)*maxTextBoundsToImageRatioX, dpi)) / float64(textExtent.X)
scaleY := float64(PointToInt26_6(float64(height)*maxTextBoundsToImageRatioY, dpi)) / float64(textExtent.Y)

fontsize := testFontSize * math.Min(scaleX, scaleY)

// draw with scaled fontsize to get the real text extent. This could also be
// done by scaling up the textExtent from the previous drawing but it's less
// precise.
c.SetFontSize(fontsize)
drawPoint = freetype.Pt(0, 0)
textExtent, err = c.DrawString(text, drawPoint)
if err != nil {
    return nil, err
}

// finally draw the centered text
drawPoint = freetype.Pt(
    int(PointToInt26_6(float64(width)/2.0, dpi)-textExtent.X/2)>>8,
    int(PointToInt26_6(float64(height)/2.0+fontsize/2.6, dpi))>>8)
```

**Comment by nigeltao** [comment]
x>>8 should be x>>6.

As I said in https://groups.google.com/forum/#!topic/golang-nuts/tr-MftD7kbo/discussion, a fixed.Point26_6 is, as its name suggests, a 26.6 fixed point. The old raster.Point was 24.8, not 26.6

BTW, you shouldn't have to call DrawString any more just to get the text extents. https://go.googlesource.com/image/+/master/font/font.go has a MeasureString method now.

**Comment by nigeltao** [comment]
https://github.com/golang/freetype/blob/master/example/drawer/main.go is an example of drawing centered text.

**Comment by fnkr** [comment]
That works, thank you so much!

**Comment by wpecker** [comment]
@nigeltao  How to bold fonts

**Comment by nigeltao** [comment]
@penhauer-xiao I don't understand your question. To write bold text, you have to use a bold font. golang/freetype doesn't do "fake bold".
