### ISSUE TITLE
go get github.com/golang/freetype failed

### ISSUE THREAD

**Issue by xming4321** [golang/freetype#28]
go get github.com/golang/freetype

package golang.org/x/image/math/fixed: unrecognized import path "golang.org/x/im
age/math/fixed"
package golang.org/x/image/font: unrecognized import path "golang.org/x/image/fo
nt"

**Comment by xming4321** [comment]
what can i do ?
Because the GFW ?

**Comment by xming4321** [comment]
what a shit ！
just GFW！

**Comment by xming4321** [comment]
ok 
add  proxy  
it works ！

**Comment by mat** [comment]
Hi @xming4321, if it works now could you close this issue?

**Comment by xming4321** [comment]
ok close
