### ISSUE TITLE
undefined: font.Metrics

### ISSUE THREAD

**Issue by ChongyuE** [golang/freetype#36]
cmd:go get github.com/golang/freetype
# github.com/golang/freetype/truetype
../../../golang/freetype/truetype/face.go:254: undefined: font.Metrics
../../../golang/freetype/truetype/face.go:257: undefined: font.Metrics

![image](https://cloud.githubusercontent.com/assets/10123859/17285237/2cdf592a-57f4-11e6-9769-47823ae4a113.png)

how to resolve this problem?

**Comment by nigeltao** [comment]
I suspect that you need to update your golang.org/x/image/font checkout. Run

go get -u golang.org/x/image/font
