### ISSUE TITLE
Right-to-Left Languages

### ISSUE THREAD

**Issue by dc0d** [golang/freetype#53]
How can `freetype` be used with RTL languages?

It renders the letters only in their capital form and draw them left to right.

**Comment by MohsenElgendy** [comment]
@dc0d any luck on implementing that?

**Comment by dc0d** [comment]
@MohsenElgendy Gave up on `freetype` and done the job using some _imagemagic_ tricks.

**Comment by hmmftg** [comment]
You can use this approach:

```
rtl := goarabic.ToGlyph(text)
_, err = c.DrawString(goarabic.Reverse(text), pt)
```

the **goarabic** package does not fully support persian characters(گ چ پ ژ), you can use my fork till then: [my fork of goarabic](https://github.com/hmmftg/goarabic)
