### ISSUE TITLE
Vertical Text

### ISSUE THREAD

**Issue by aragonet** [golang/freetype#56]
Is there a way to set a text in vertical?

I'd really appreciate that...

Thanks

**Comment by nigeltao** [comment]
Not currently. Sorry.

**Comment by Wohlstand** [comment]
You can just load every glyph individually and draw them yourself where you want (for example, put them randomly on any position of the screen). Means, for vertical text, you need to iterate Y offset by adding the height and some spacing between of letters, and keep X offset be same (or align glyphs to center if needed).

**Comment by 1l0** [comment]
Looks like that `Glyph` already has included a `Vmetric` in [phantomPoints[2,3]](https://github.com/golang/freetype/blob/master/truetype/glyph.go#L199). So somehow you could achieve vertical text in CJK fonts if you write the proper rasterizer for it... I want it too.

**Comment by aragonet** [comment]
Ok thanks for your help.
At the end I made it by drawing the fonts in horizontal and then rotate the image...
