### ISSUE TITLE
rendering simple/small fonts on small LCD

### ISSUE THREAD

**Issue by cbrake** [golang/freetype#69]
I have an application where I'd like to render the tight pixel font (https://www.dafont.com/tight-pixel.font) on a small 128x64 LCD with a 1-bit color space. Attached is an image showing the font rendered with golang/freetype (the example program), and gimp. I'd like it to look more like the gimp rendering (with no anti-aliasing, etc). Is there any way to do this with golang/freetype?

I've also looked at https://github.com/pbnjay/pixfont and it works OK, but it has an issue with calculating string width of using variable width fonts, plus it is more work to use the font.

Appreciate any pointers.

(note, most browsers and image viewers smooth the below image, so it is best viewed in gimp if you want to see exactly what is going on at the pixel level)

![tight-pixel-rendering](https://user-images.githubusercontent.com/402813/51714996-060dbe00-2005-11e9-9153-a002f419c25e.png)

**Comment by frranck** [comment]
Hi, did you figure out @cbrake ?

**Comment by cbrake** [comment]
I ended up using https://github.com/pbnjay/pixfont -- I had to make a few tweaks that have been upstreamed. It is a little work to use, but in the end does the job.
